Image Processing Update
PalouseRobosub/robosub-2018 pull request #102
Opened 2016-12-08 21:31 UTC by skallaher

The vision can now mask multiple color ranges and or them together as well as publishing a visionPosArray. The previous vision launch file is now the camera launch file. Also, fixed #101.

2016-12-08 23:28 UTC, irwineffect requested changes
looks good, just needs some small tweaks

2016-12-08 23:28 UTC, irwineffect commented on launch/vision.launch
> +        <param name="subTopic" value="buoys/red"/>
can you change this to use topic remapping to set the topic name?

2016-12-08 23:28 UTC, irwineffect commented on src/vision/VisionProcessor.cpp
> +    ROS_DEBUG_STREAM("Copied to red");
please remove dead code

2016-12-09 03:24 UTC, skallaher commented
I have tried to rebase onto dev, however, git says that there's a whitespace error on some line. I don't know why this is.

2016-12-09 22:16 UTC, irwineffect requested changes

2016-12-09 22:16 UTC, irwineffect commented on src/vision/Vision.cpp
>      ros::Subscriber rightCamSub = n.subscribe("/camera/left/image", 1, rightCamCallback);
Can you remove the leading '/' on the topic? This makes the topic global, instead of relative.

2016-12-09 22:16 UTC, irwineffect commented on src/vision/Vision.cpp
> +    pub = n.advertise<robosub::visionPosArray>("/vision/output_default" + topic, 1);
Can you remove the leading '/'?

2016-12-09 22:29 UTC, skallaher commented
Rebased on dev

2016-12-09 23:50 UTC, irwineffect approved these changes

2016-12-09 23:50 UTC, merged