Working Maestro Thruster test
PalouseRobosub/robosub-2018 pull request #103
Opened 2016-12-08 23:32 UTC by irwineffect

2016-12-08 23:33 UTC, irwineffect commented
The test should pass once #104 is merged in.

2016-12-09 00:43 UTC, bkallaher requested changes
Fails in the linter...

2016-12-09 00:43 UTC, bkallaher commented on src/movement/test/CMakeLists.txt
> +target_link_libraries(test_maestro_thruster serial test_tools ${catkin_LIBRARIES} ${GTEST_LIBRARIES})
The naming for this executable don't match those of the sabertooth.

2016-12-09 00:43 UTC, bkallaher commented on src/movement/test/test_maestro_thruster.cpp
> +    /////getchar();
Do these comments need to be here?

2016-12-09 00:43 UTC, bkallaher commented on src/movement/test/test_maestro_thruster.cpp
> +    ROS_INFO("all setup, press enter");
There is no getch so enter isn't needed.

2016-12-09 00:43 UTC, bkallaher commented on src/movement/test/test_maestro_thruster.cpp
> +double max_speed = 0.6;
Is there really a need for globals?

2016-12-09 00:43 UTC, bkallaher commented on src/movement/test/test_maestro_thruster.cpp
> +
Extra whitespace

2016-12-09 06:51 UTC, skallaher commented on src/movement/test/test_maestro_thruster.cpp
> +double max_speed = 0.6;
At least the `max_speed` value was just temporary to get the test in a working state.

2016-12-09 22:58 UTC, irwineffect commented on src/movement/test/CMakeLists.txt
> +target_link_libraries(test_maestro_thruster serial test_tools ${catkin_LIBRARIES} ${GTEST_LIBRARIES})
fixed!

2016-12-09 22:59 UTC, irwineffect commented on src/movement/test/test_maestro_thruster.cpp
> +double max_speed = 0.6;
Yeah, in the future there will be more tests, they will use these variables.

2016-12-09 22:59 UTC, irwineffect commented on src/movement/test/test_maestro_thruster.cpp
> +
fixed

2016-12-09 23:47 UTC, irwineffect commented on src/movement/test/test_maestro_thruster.cpp
> +    ROS_INFO("all setup, press enter");
fixed

2016-12-09 23:47 UTC, irwineffect commented on src/movement/test/test_maestro_thruster.cpp
> +    /////getchar();
fixed

2016-12-10 01:37 UTC, skallaher requested changes

2016-12-10 01:37 UTC, skallaher commented on src/movement/test/test_thruster_maestro.cpp
> +//confirm that the received values are the same as the sent values.
This comment claims to be testing the `serial_subscriber` example.

2016-12-10 01:37 UTC, skallaher commented on src/movement/test/test_thruster_maestro.cpp
> +double max_speed = 0.6;
Will this be made into a parameter in future? As well as in the unit under test?

2016-12-10 01:37 UTC, skallaher commented on src/movement/test/test_thruster_maestro.cpp
> +//insert tests here
Perhaps describe the test being run here.

2016-12-10 01:37 UTC, skallaher commented on src/movement/test/test_thruster_maestro.cpp
> +    uint8_t maestro_data[256] = {0};
I had the same question in the sabertooth test. Why is this an arbitrary number? Isn't this a guaranteed size given correct responses?

2016-12-10 01:37 UTC, skallaher commented on src/movement/test/test_thruster_maestro.cpp
> +        ROS_WARN("raw_vals: %x, %x", maestro_data[2], maestro_data[3]);
Are these two outputs the correct logger level for what they are?

2016-12-10 01:37 UTC, skallaher commented on src/movement/test/test_thruster_maestro.cpp
> +    ROS_INFO("test over, waiting");
What is this waiting on?

2016-12-10 01:37 UTC, skallaher commented on src/movement/test/test_thruster_maestro.cpp
> +    ros::init(argc, argv, "maestro_launch_test");
Would this be good to rename to reflect the refactoring of the executable?

2016-12-10 01:37 UTC, skallaher commented on src/movement/test/test_thruster_maestro.cpp
> +        exit(1);
Does exiting this way actually fail the test?

2016-12-10 01:37 UTC, skallaher commented on src/movement/test/thruster_maestro.test
> +    <test test-name="test_maestro_thruster" pkg="robosub" type="test_maestro_thruster" />
The type doesn't match the new executable name, is this intended?

2016-12-11 22:40 UTC, bkallaher commented on src/movement/test/thruster_maestro.test
> +    <test test-name="test_maestro_thruster" pkg="robosub" type="test_maestro_thruster" />
Fixed

2016-12-11 22:40 UTC, bkallaher approved these changes

2016-12-11 22:43 UTC, bkallaher commented on src/movement/test/test_thruster_maestro.cpp
> +double max_speed = 0.6;
It should be in the control parameters

2016-12-11 22:45 UTC, bkallaher commented on src/movement/test/test_thruster_maestro.cpp
> +        exit(1);
Any exit value other than 0 will fail the test.

2016-12-11 22:51 UTC, bkallaher commented on src/movement/test/test_thruster_maestro.cpp
> +    uint8_t maestro_data[256] = {0};
When it comes to any type of read or write on a communication bus you should always allocate more than the expected data. In a single read the program could take in more than one packet. In many cases (IP for example) it is required that an application read in all data available.

2016-12-11 23:02 UTC, bkallaher commented on src/movement/test/test_thruster_maestro.cpp
> +//insert tests here
Added.

2016-12-11 23:03 UTC, bkallaher commented on src/movement/test/test_thruster_maestro.cpp
> +    ROS_INFO("test over, waiting");
@irwineffect: is it still in need of the wait at the end?

2016-12-11 23:05 UTC, bkallaher commented on src/movement/test/test_thruster_maestro.cpp
> +        ROS_WARN("raw_vals: %x, %x", maestro_data[2], maestro_data[3]);
Logging isn't done when the test is actually run so it really doesn't matter.

2016-12-11 23:07 UTC, bkallaher commented on src/movement/test/test_thruster_maestro.cpp
> +    ros::init(argc, argv, "maestro_launch_test");
As long as the name is unique there really isn't a need to change the running node name here.

2016-12-12 23:16 UTC, skallaher approved these changes

2016-12-12 23:37 UTC, merged