fixed control system bug from #119
PalouseRobosub/robosub-2018 pull request #127
Opened 2016-12-24 20:59 UTC by irwineffect

2016-12-24 21:37 UTC, skallaher requested changes

2016-12-24 21:37 UTC, skallaher commented on src/movement/control_system.cpp
> +                            this->goals[i] = this->goals[i];
You're assigning this value to itself... This is unnecessary.

2016-12-24 21:37 UTC, skallaher commented on src/movement/control_system.cpp
>                       */
This comment doesn't seem quite as accurate, perhaps refactor it.

2016-12-24 21:54 UTC, irwineffect commented on src/movement/control_system.cpp
>                       */
This is still correct, all I've done is update the logic to work as expected for a relative change of zero.

2016-12-24 21:55 UTC, irwineffect commented on src/movement/control_system.cpp
> +                            this->goals[i] = this->goals[i];
I'm just being explicit, I suppose I could have an empty if statement here with a comment. I'll fix that.

2016-12-24 22:19 UTC, skallaher approved these changes
Looks good!

2016-12-24 22:49 UTC, bkallaher requested changes
Just a small fix.

2016-12-24 22:49 UTC, bkallaher commented on src/movement/control_system.cpp
> +                        {
Maybe this if else should be switched with no else statement, just a comment about what it would be.

2016-12-25 01:08 UTC, bkallaher approved these changes
Looks good.

2016-12-25 01:14 UTC, merged