Make Roulette wheel AI to use parameters
PalouseRobosub/robosub-2018 pull request #414
Opened 2018-07-25 04:07 UTC by Sindorman

Due to recent tests of roulette wheel AI, it is found that default timeout parameters are not good for real world. This PR makes AI to use loaded parameters for timeouts. Summary:

- Adds parameters for simulator into `ai.yaml` for timeouts

- Adds parameters to real world `ai_pool.yml` for timeouts

- Changes AI code to use parameters for timeouts.

2018-07-25 06:21 UTC, ryan-summers requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: all files reviewed, 2 unresolved discussions (waiting on @Sindorman)

___
*[param/ai.yaml, line 45 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4CEk7hiRirR4ZToH:-LIF4CEl4ARXjWrmoqx2:b5cfnlw) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/param/ai.yaml#L45)):*
> ```YAML
>         yaw_relative: 60
>         forward_speed: 4
> # roulette wheel AI variables. They are all time in seconds
> ```

I'm a fan of appending unit information to the actual labels themselves to denote what they specify. It makes the code and config more understandable. E.g. it would be `stabilize_s`. What do you think?
___
*[param/ai_pool.yaml, line 47 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF51CH9Cf5wvzbSEH8:-LIF51CH9Cf5wvzbSEH9:bazp7vj) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/param/ai_pool.yaml#L47)):*
> ```YAML
>     move_forward_single:
>         distanceGoal: 0.007
> # roulette wheel AI variables. They are all time in seconds
> ```

Whats the difference between ai_pool.yaml and ai.yaml? These names should probably be `ai_simulator.yaml` and `ai_gibbs.yaml` or something similar.
___
*[src/ai/smach_roulette.py, line 186 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4_493XbxteabU8iA:-LIF4_493XbxteabU8iB:b-grxi5h) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/src/ai/smach_roulette.py#L186)):*
> ```Python
>         self.depth_time = rospy.get_param("ai/roulette_wheel/go_to_depth")
>         self.stabilize_time = rospy.get_param("ai/roulette_wheel/stabilize")
>         self.center_downward_camera_time = \
> ```

You should be adding documentation to the code like the classes above (See CenterDownwardCamera) for class attributes.


<!-- Sent from Reviewable.io -->

2018-07-25 07:29 UTC, Sindorman reviewed
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Sindorman)

___
*[param/ai_pool.yaml, line 47 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF51CH9Cf5wvzbSEH8:-LIFKTU4B7Ox4vdQVWBM:b7kqg9z) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/param/ai_pool.yaml#L47)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Whats the difference between ai_pool.yaml and ai.yaml? These names should probably be `ai_simulator.yaml` and `ai_gibbs.yaml` or something similar.
</blockquote></details>

They are being renamed in #409 PR
___
*[src/ai/smach_roulette.py, line 186 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4_493XbxteabU8iA:-LIFKbZT5YFMvvcY__oK:b-4ftju2) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/src/ai/smach_roulette.py#L186)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

You should be adding documentation to the code like the classes above (See CenterDownwardCamera) for class attributes.
</blockquote></details>

What kind of documentation do you suggest for these 4 lines of code. I have added a comment explaining that these 4 lines of code are loading parameters for timeout variable which are integers that represent seconds.


<!-- Sent from Reviewable.io -->

2018-07-25 09:00 UTC, ryan-summers requested changes
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Sindorman and @ryan-summers)

___
*[src/ai/smach_roulette.py, line 186 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4_493XbxteabU8iA:-LIFeJ6Y79cNJsuwAoYm:b-cr4o26) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/src/ai/smach_roulette.py#L186)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

What kind of documentation do you suggest for these 4 lines of code. I have added a comment explaining that these 4 lines of code are loading parameters for timeout variable which are integers that represent seconds.
</blockquote></details>

You have added attributes to the CenterAbove class (specifically, `self.depth_time`, `self.stabilize_time`, and `self.center_downward_cam_time`. Can you add attribute documentation for each added attribute in the class documentation? For an example, look at lines 97-104


<!-- Sent from Reviewable.io -->

2018-07-25 20:45 UTC, Sindorman reviewed
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Sindorman)

___
*[src/ai/smach_roulette.py, line 186 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4_493XbxteabU8iA:-LIIAwfHAxqk_Jv-02WG:b-8kemnh) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/src/ai/smach_roulette.py#L186)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

You have added attributes to the CenterAbove class (specifically, `self.depth_time`, `self.stabilize_time`, and `self.center_downward_cam_time`. Can you add attribute documentation for each added attribute in the class documentation? For an example, look at lines 97-104
</blockquote></details>

I can add documentation, but I thought that variables are self explanatory with their names, and the comment above them


<!-- Sent from Reviewable.io -->

2018-07-26 08:45 UTC, ryan-summers approved these changes
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Sindorman and @ryan-summers)

___
*[src/ai/smach_roulette.py, line 186 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4_493XbxteabU8iA:-LIKk_1r8jFNhzNxRkbC:bhhyhrl) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/src/ai/smach_roulette.py#L186)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

I can add documentation, but I thought that variables are self explanatory with their names, and the comment above them
</blockquote></details>

It's generally not good practice to assume code will be understandable - this is following Google's python documentation styles (http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). If you don't want to add them, I'm not going to stop you since its so close to competition.


<!-- Sent from Reviewable.io -->

2018-07-29 06:41 UTC, Sindorman reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Sindorman)

*[a discussion](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIZkyg8CHkAfr76GBG_:-LIZkyg8CHkAfr76GBGa:b-ux6d0s) (no related file):*
I have added documentation and noticed that there was one duplicated line. Review again please 

---


<!-- Sent from Reviewable.io -->

2018-09-30 22:45 UTC, daymare requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: all files reviewed, 3 unresolved discussions (waiting on @daymare and @Sindorman)

___
*[param/ai.yaml, line 45 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4CEk7hiRirR4ZToH:-LNgdAgVEEY8_3WwsJYR:b-ykwrjy) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/param/ai.yaml#L45)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I'm a fan of appending unit information to the actual labels themselves to denote what they specify. It makes the code and config more understandable. E.g. it would be `stabilize_s`. What do you think?
</blockquote></details>

I'd be happy if we called it something like stabilize_sec, yaw_relative_deg, etc.
___
*[param/ai_pool.yaml, line 48 at r3](https://reviewable.io/reviews/palouserobosub/robosub/414#-LNgdimf3nH7o9_TvYAF:-LNgdimf3nH7o9_TvYAG:b-464aaj) ([raw file](https://github.com/palouserobosub/robosub/blob/6cc77fcc0d31ee1108179d540e535f50744dd047/param/ai_pool.yaml#L48)):*
> ```YAML
>         distanceGoal: 0.007
> # roulette wheel AI variables. They are all time in seconds
>     roulette_wheel:
> ```

Same as above can we rename these to include variable type?


<!-- Sent from Reviewable.io -->

2018-10-01 19:47 UTC, Sindorman reviewed
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: all files reviewed, 3 unresolved discussions (waiting on @Sindorman)

___
*[param/ai.yaml, line 45 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4CEk7hiRirR4ZToH:-LNl9t15EuHGmV6QzOPG:bb71kmx) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/param/ai.yaml#L45)):*
<details><summary><i>Previously, daymare (Daylan Kelting) wrote…</i></summary><blockquote>

I'd be happy if we called it something like stabilize_sec, yaw_relative_deg, etc.
</blockquote></details>

Okay


<!-- Sent from Reviewable.io -->

2018-10-01 20:47 UTC, Sindorman reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Sindorman and @daymare)

___
*[param/ai_pool.yaml, line 48 at r3](https://reviewable.io/reviews/palouserobosub/robosub/414#-LNgdimf3nH7o9_TvYAF:-LNlNenjCmG2_uj3Zfnj:bb6un1j) ([raw file](https://github.com/palouserobosub/robosub/blob/6cc77fcc0d31ee1108179d540e535f50744dd047/param/ai_pool.yaml#L48)):*
<details><summary><i>Previously, daymare (Daylan Kelting) wrote…</i></summary><blockquote>

Same as above can we rename these to include variable type?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2018-10-03 11:07 UTC, ryan-summers reviewed
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Sindorman and @daymare)

___
*[param/ai.yaml, line 45 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4CEk7hiRirR4ZToH:-LNta2yT7KVkPftQ2ay_:b5es7gw) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/param/ai.yaml#L45)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Okay
</blockquote></details>

I see that you appended `_timeout` here, but I think we want specifically `_secs` or `_sec` - `_timeout` may imply minutes, hours, milliseconds, etc. Also, above, we would want `yaw_error_degrees`
___
*[param/ai_pool.yaml, line 48 at r3](https://reviewable.io/reviews/palouserobosub/robosub/414#-LNgdimf3nH7o9_TvYAF:-LNtaJ48CEyiUrjtm4ul:brkffeo) ([raw file](https://github.com/palouserobosub/robosub/blob/6cc77fcc0d31ee1108179d540e535f50744dd047/param/ai_pool.yaml#L48)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Ditto on my above comment.
___
*[src/ai/smach_roulette.py, line 7 at r4](https://reviewable.io/reviews/palouserobosub/robosub/414#-LNtaoXZDj2tOjq78Jzh:-LNtaoXZDj2tOjq78Jzi:b-wtu468) ([raw file](https://github.com/palouserobosub/robosub/blob/cf2fe668aff21f1a0602508ed90a56515f22757c/src/ai/smach_roulette.py#L7)):*
> ```Python
> from start_switch import start_switch
> from roulette_states import *
> from basic_states import *
> ```

I personally prefer to not use `import *` and to instead either: explicitly import used classes, or call out the source file when defining (e.g. `basic_states.GoToDepth()`. This helps future readers understand where a class is defined. As it stands now, it can be either in roulette_states.py or in basic_states.py - That's why the original code explicitly called out `basic_states.GoToDepth`


<!-- Sent from Reviewable.io -->

2018-10-03 11:08 UTC, ryan-summers requested changes
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Sindorman and @daymare)

___
*[src/ai/smach_roulette.py, line 6 at r4](https://reviewable.io/reviews/palouserobosub/robosub/414#-LNtbGYdE4oQy45OfMQP:-LNtbGYdE4oQy45OfMQQ:b-37ja7o) ([raw file](https://github.com/palouserobosub/robosub/blob/cf2fe668aff21f1a0602508ed90a56515f22757c/src/ai/smach_roulette.py#L6)):*
> ```Python
> import smach_ros
> from start_switch import start_switch
> from roulette_states import *
> ```

You did not add `roulette_states.py` to this PR. As it currently stands, this PR will break the Roulette AI


<!-- Sent from Reviewable.io -->

2018-10-03 16:59 UTC, Sindorman reviewed
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Sindorman and @daymare)

___
*[param/ai.yaml, line 45 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4CEk7hiRirR4ZToH:-LNwMXLP1bFEUtzbmJIP:bs7lqkl) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/param/ai.yaml#L45)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I see that you appended `_timeout` here, but I think we want specifically `_secs` or `_sec` - `_timeout` may imply minutes, hours, milliseconds, etc. Also, above, we would want `yaw_error_degrees`
</blockquote></details>

I will change it.
___
*[src/ai/smach_roulette.py, line 6 at r4](https://reviewable.io/reviews/palouserobosub/robosub/414#-LNtbGYdE4oQy45OfMQP:-LNwMMD0BoMPnkOFS0B4:bhm0qua) ([raw file](https://github.com/palouserobosub/robosub/blob/cf2fe668aff21f1a0602508ed90a56515f22757c/src/ai/smach_roulette.py#L6)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

You did not add `roulette_states.py` to this PR. As it currently stands, this PR will break the Roulette AI
</blockquote></details>

This works with the master. Because my AI rework PR has moved everything to roulette_states and I have rebased this branch.
___
*[src/ai/smach_roulette.py, line 7 at r4](https://reviewable.io/reviews/palouserobosub/robosub/414#-LNtaoXZDj2tOjq78Jzh:-LNwLWxx5q5BpbCAMZ9M:bmp2g55) ([raw file](https://github.com/palouserobosub/robosub/blob/cf2fe668aff21f1a0602508ed90a56515f22757c/src/ai/smach_roulette.py#L7)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I personally prefer to not use `import *` and to instead either: explicitly import used classes, or call out the source file when defining (e.g. `basic_states.GoToDepth()`. This helps future readers understand where a class is defined. As it stands now, it can be either in roulette_states.py or in basic_states.py - That's why the original code explicitly called out `basic_states.GoToDepth`
</blockquote></details>

That is a good point! I will remake imports


<!-- Sent from Reviewable.io -->

2018-10-03 17:13 UTC, Sindorman reviewed
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Sindorman and @daymare)

___
*[param/ai.yaml, line 45 at r1](https://reviewable.io/reviews/palouserobosub/robosub/414#-LIF4CEk7hiRirR4ZToH:-LNuudb18UkJv3uzXwxW:bzce34y) ([raw file](https://github.com/palouserobosub/robosub/blob/e5ef854679d271ec0ebc462214b2607f8bcc2494/param/ai.yaml#L45)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

I will change it.
</blockquote></details>

Changed it, `yaw_error_degrees` is a  different AI that was pushed in different PR. I will make separate PR for renaming these vars, keeping our PRs as atomic as possible.


<!-- Sent from Reviewable.io -->

2018-10-03 17:13 UTC, Sindorman reviewed
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Sindorman and @daymare)



<!-- Sent from Reviewable.io -->

2018-10-25 22:53 UTC, brennanpeter requested changes
> Reviewed 1 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/palouserobosub/robosub/414)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @Sindorman and @daymare)

___
*[src/ai/smach_roulette.py, line 26 at r6](https://reviewable.io/reviews/palouserobosub/robosub/414#-LPhQ7zD1NGYNnPcXLkG:-LPhQ7zD1NGYNnPcXLkH:b-xpsrtz) ([raw file](https://github.com/palouserobosub/robosub/blob/f91ed9f85a6b3ebd93092748598c3304dad73720/src/ai/smach_roulette.py#L26)):*
> ```Python
>                 rospy.get_param("ai/roulette_wheel/go_to_depth_timeout_sec")
>         self.stabilize_timeout_sec = \
>                 rospy.get_param("ai/roulette_wheel/stabilize_timeout_sec")
> ```

I'm no expert on Smach but should this line be in here twice?


<!-- Sent from Reviewable.io -->

2020-07-22 01:40 UTC, closed without merging