Zach/ftdi wrapper
PalouseRobosub/robosub-2018 pull request #53
Opened 2016-10-22 23:51 UTC by AtomicCharge

2016-10-22 23:54 UTC, irwineffect requested changes

2016-10-22 23:54 UTC, irwineffect commented on src/utility/ftdi_serial.hpp
> +		bool read(std::string& msg, unsigned int numChars = 0);
Can we change these std::strings to std::vector<uint8_t>?

2016-10-22 23:54 UTC, irwineffect commented on src/utility/ftdi_serial.hpp
> +		DWORD m_baud_rate = 9600;
Is it possible to use fixed-width datatypes like unint32_t?

2016-10-22 23:54 UTC, irwineffect commented on src/utility/ftdi_serial.cpp
> +	std::vector<std::string> FTDISerial::m_dev_list;
convert all tabs to spaces

2016-10-22 23:55 UTC, bkallaher commented on src/utility/ftdi_serial.cpp
> +	std::vector<std::string> FTDISerial::m_dev_list;
Fixed in b95aaa3

2016-10-22 23:56 UTC, irwineffect commented on src/utility/ftdi_serial.cpp
> +	std::vector<std::string> FTDISerial::m_dev_list;
looks good here!

2016-10-23 19:29 UTC, AtomicCharge commented
Implemented requested changes.

2016-10-26 23:52 UTC, irwineffect approved these changes
Looks good!

2016-10-26 23:59 UTC, irwineffect requested changes
I added this to the build and tried to compile, and it won't compile because I don't have ftd2xx.h. We'll want to work together to add that dependency to our robosub debian repo before this gets merged into dev.

2016-11-02 00:02 UTC, irwineffect approved these changes

2016-11-02 00:36 UTC, skallaher commented
@bkallaher mentioned adding I2C support. Would that be feasible?

2016-11-02 00:41 UTC, merged