Added image publisher node.
PalouseRobosub/robosub-2018 pull request #57
Opened 2016-10-29 21:59 UTC by BigDCross

This reads from shared memory and publishes
the left and right camera images.
Also added the SharedImageReader and SharedImageWriter
libraries though the writer is currently unused.

2016-10-29 22:00 UTC, BigDCross commented
We'll also need to add the
ros-indigo-image-transport 
and probably the 
ros-indigo-image-transport-plugins
packages to the robosub build.

2016-11-01 00:49 UTC, irwineffect commented
I added those two packages to our robosub package!

2016-11-01 22:07 UTC, irwineffect requested changes

2016-11-01 22:07 UTC, irwineffect commented on src/vision/image_publisher.cpp
> +        sensor_msgs::ImagePtr r_msg = cv_bridge::CvImage(std_msgs::Header(), "bgr8", r).toImageMsg();
Can we rename the topics to camera/left/image_raw and camera/right/image_raw, this is the standard naming scheme.

2016-11-01 22:22 UTC, BigDCross commented on src/vision/image_publisher.cpp
> +        sensor_msgs::ImagePtr r_msg = cv_bridge::CvImage(std_msgs::Header(), "bgr8", r).toImageMsg();
Ok I renamed them. The _raw part should be added by the image transport.

2016-11-01 22:29 UTC, irwineffect approved these changes

2016-11-01 22:30 UTC, merged