Image Processing beginnings
PalouseRobosub/robosub-2018 pull request #78
Opened 2016-11-16 03:39 UTC by skallaher

The vision processing is currently split into a node and a class. The class handles conversion to OpenCv and performing color filtering. This is done with the following filters:

**Median Blur**: To create some smoothness
**In Range**: Color thresholding based upon parameters (The parameters will need to be altered later)
**Open Filter**: To reduce small noise particles

### Future changes proposed
- Refine and/or add filters to improve performance.
- Pass off workload to the [GPU using OpenCv](http://docs.opencv.org/2.4/modules/gpu/doc/gpu.html)
- Refine color ranges for more accurate vision
- Allow for multiple ranges for multiple colors and for red which is on both ends of the scale
- Implement undistortion and calibration
- See if OpenCv 3 will work as the system currently uses 2.4
- Make design decisions about reporting multiple colors found (e.g. one node per object, nodelets, or multiple class instances in one node)
- Horizon detection for elimination of anything above the surface of the water
- Stereoscopic processing

2016-11-18 05:04 UTC, bkallaher requested changes

2016-11-18 05:04 UTC, bkallaher commented on src/vision/Vision.cpp
> +    pub.publish(outMsg);
What happens when no contours are found? The outMsg isn't initialized with any values.

2016-11-18 05:04 UTC, bkallaher commented on src/vision/Vision.cpp
> +    robosub::visionPos outMsg;
Again sending out an uninitialized message...

2016-11-18 05:04 UTC, bkallaher commented on src/vision/Vision.cpp
> +    ros::Subscriber rightCamSub = n.subscribe("/camera/left/image", 1, rightCamCallback);
Are the topics switched due to the sample video that you had?

2016-11-18 05:04 UTC, bkallaher commented on src/vision/VisionProcessor.cpp
> +    medianBlur(mask, mask, 3);
Is there a reason to blur an empty Mat?

2016-11-18 05:04 UTC, bkallaher commented on src/vision/VisionProcessor.hpp
> +#include <ros/ros.h>
You include this in Vision.cpp using quotes yet here you use the <>. Is it in the std library path or not?

2016-11-18 05:04 UTC, bkallaher commented on src/vision/VisionProcessor.py
> +    imHeight = len(image[0])
There is a better way to get the size of a numpy array see this thread on [StackOverflow](http://stackoverflow.com/questions/14847457/how-do-i-find-the-length-or-dimensions-size-of-a-numpy-matrix-in-python)

2016-11-18 05:23 UTC, skallaher commented on src/vision/Vision.cpp
> +    pub.publish(outMsg);
It will publish an empty message, which is the desired behavior.

2016-11-18 05:23 UTC, skallaher commented on src/vision/Vision.cpp
> +    robosub::visionPos outMsg;
Currently, no work is being done on the right camera. This will probably be modified in future.

2016-11-18 05:24 UTC, skallaher commented on src/vision/Vision.cpp
> +    ros::Subscriber rightCamSub = n.subscribe("/camera/left/image", 1, rightCamCallback);
Yes, that is why.

2016-11-18 05:26 UTC, skallaher commented on src/vision/VisionProcessor.hpp
> +#include <ros/ros.h>
I will remove it from Vision.cpp, didn't notice the redundancy. This is proper according to [this question](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename).

2016-11-18 05:26 UTC, skallaher commented on src/vision/VisionProcessor.py
> +    imHeight = len(image[0])
The python vision processing is becoming deprecated soon and I'm not sure if I should move it to the examples or just remove it.

2016-11-18 06:17 UTC, skallaher commented on src/vision/VisionProcessor.cpp
> +    medianBlur(mask, mask, 3);
Will fix. I had the blur after the inRange, but then moved it and forgot to change this.

2016-11-18 23:31 UTC, bkallaher commented on src/vision/VisionProcessor.py
> +    imHeight = len(image[0])
James says do a git rm on the file and make a new commit so that it is still in the git history.

2016-11-18 23:33 UTC, bkallaher commented on src/vision/VisionProcessor.hpp
> +#include <ros/ros.h>
I already knew what the difference was it was just a question of whether or not it was in the library search path for the cmake build.

2016-11-19 07:13 UTC, bkallaher approved these changes

2016-11-25 01:33 UTC, merged