Added simulator bridge that publishes sub pos, orientation, and depth
PalouseRobosub/robosub-2018 pull request #84
Opened 2016-12-02 08:22 UTC by BigDCross

2016-12-02 17:41 UTC, skallaher approved these changes

2016-12-02 17:41 UTC, skallaher commented on src/sensors/simulator_bridge.cpp
> +    geometry_msgs::Vector3 lin_accel_msg;
You commented out the publisher for the `lin_accel` shouldn't this also be commented out?

2016-12-02 17:44 UTC, skallaher commented
It looks like the Travis build failed because cmake couldn't find gazebo_msgs.

2016-12-02 20:44 UTC, BigDCross commented
We'll need to add ros-indigo-gazebo7-msgs to the apt repo.

2016-12-03 10:10 UTC, BigDCross commented
One more commit to review! I added a publisher for simulator object positions (useful for localization, ai, unit tests). Technically this is redundant since this information is found in the gazebo_msgs/ModelStates but it should simplify things a lot.

2016-12-03 22:22 UTC, ryan-summers requested changes
Remove commented lines of code and all unneeded newlines.

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +    if(!nh.getParam("control/rate", rate))
Add brackers

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +	ros::Subscriber orient_sub = nh.subscribe("gazebo/model_states", 1, modelStatesCallback);
unindent

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +    // at a very high rate and we don't need every message
Period

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +    // You can throttle subscriber input in other ways but
comma

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +    // doesn't require extra packages or anything
Period

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +//ros::Publisher lin_accel_pub;
Remove commented out lines of code  if you plan on adding them in future pull requests.

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +    //geometry_msgs::Vector3 lin_accel_msg;
Remove

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +            // Calculate index
Calculate index in array from the iterator element.

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +            auto idx = std::distance(msg.name.begin(), it);
Don't make this auto for clarity.

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +    //lin_accel_pub.publish(lin_accel_msg);
Remove commented out line and newline above.

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +	ros::init(argc, argv, "simulator_bridge");
Fix indentation.

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +    obstacle_pos_pub = nh.advertise<robosub::ObstaclePosArray>("obstacle_positions", 1);
change topic to obstacles/positions

2016-12-03 22:22 UTC, ryan-summers commented on src/sensors/simulator_bridge.cpp
> +    //lin_accel_pub = nh.advertise<geometry_msgs::Vector3>("lin_accel", 1);
Remove commented out line of code.

2016-12-04 00:41 UTC, ryan-summers approved these changes
Everything is looking good from here pending addition of the gazebo packages to the robosub packages.

2016-12-04 01:00 UTC, merged