Add BNO055 Driver
PalouseRobosub/robosub-2018 pull request #87
Opened 2016-12-04 03:44 UTC by ryan-summers

This pull request is for the addition of the BNO055 UART driver to be added to dev. Additionally, this pull request modifies serial.Read() so that the timeout within the serial class is observed even when no bytes are recieved.

2016-12-05 02:40 UTC, irwineffect commented
I'm reading through this, but it's such a huge pull request it's going to take a while.

2016-12-06 04:37 UTC, ryan-summers commented
Just corrected an issue after dev testing the BNO055. There are cases where the internal buffer on the BNO overflows and it will inform you. There was a small issue with my macro handling so I wasn't getting the error and the serial port would intermittently hang. I've figured it out and have the BNO outputting at a steady 50Hz now.

2016-12-07 23:58 UTC, irwineffect requested changes
Overall looks pretty good. A few spelling mistakes and I noted some filename/location changes.

A few of my comments were just pointing out some functions that idk if it really needs to be there, but you don't have to remove them.

2016-12-07 23:58 UTC, irwineffect commented on src/utility/serial.hpp
> +        int Flush();
can you add a comment here saying that this discards both the input and output buffers?

2016-12-07 23:58 UTC, irwineffect commented on src/utility/serial.cpp
> +            double time = 0;
you'll want to use a ros::Time datatype here for the time variable, not a double.

2016-12-07 23:58 UTC, irwineffect commented on src/utility/serial.cpp
> +            double time = 0;
Alternative way to write this with the ros timing mechanisms would be:
```c++
ros::Time exit_time = ros::Time::now() + ros::Duration(0.5);
while (QueryBuffer() == 0 && ros::Time::now() < exit_time)
{     
    ros::Duration(0.02).sleep()
}

```

2016-12-07 23:58 UTC, irwineffect commented on src/sensors/sensor.cpp
> +            "Failed to load acclerometer calibration offset.");
misspelled "accelerometer" in the fatal abort message.

2016-12-07 23:58 UTC, irwineffect commented on src/sensors/sensor.cpp
> +            "Failed to load magnometer calibration offset.");
misspelled "magnetometer" in the parameter name and abort message.

2016-12-07 23:58 UTC, irwineffect commented on src/sensors/sensor.cpp
> +
As a general comment, for some parameters it might not be a bad idea to just load some default value if things aren't set in the parameter server, and log a warning that the default value is getting used.

2016-12-07 23:58 UTC, irwineffect commented on param/cobalt.yaml
> +    magnometer:
should be "magnetometer"

2016-12-07 23:58 UTC, irwineffect commented on src/sensors/bno_example.cpp
> +#include "sensors/Bno055.h"
can we move this file to the examples directory? Or is it even necessary now that we have the other program?

2016-12-07 23:58 UTC, irwineffect commented on src/sensors/sensor.cpp
> +#include "robosub/Euler.h"
Can we name this file to be more explicit? Something like "bno055_sensor.cpp"?

2016-12-07 23:58 UTC, irwineffect commented on src/sensors/Bno055.cpp
> +    int Bno055::init(bool use_external_crystal)
Is there ever a reason why we wouldn't want to use the external crystal?

2016-12-07 23:58 UTC, irwineffect commented on src/sensors/Bno055.cpp
> +    int Bno055::setPowerMode(PowerMode mode)
Is there a need to allow the user set the power mode? Just default to normal mode.

2016-12-07 23:58 UTC, irwineffect commented on src/sensors/Bno055.cpp
> +    int Bno055::setPitchMode(Bno055::PitchMode mode)
Is this configuration necessary?

2016-12-07 23:58 UTC, irwineffect commented on src/sensors/Bno055.cpp
> +    int Bno055::setOutputFormat(Bno055::Sensor sensor, Bno055::Format format)
Can we just default to degrees and F?

2016-12-08 00:10 UTC, ryan-summers commented on src/utility/serial.hpp
> +        int Flush();
I'll add it in the CPP file!

2016-12-08 00:21 UTC, ryan-summers commented on src/sensors/sensor.cpp
> +            "Failed to load acclerometer calibration offset.");
Copypasta fail that I fixed in code but not comments. Good catch!

2016-12-08 00:40 UTC, ryan-summers commented on src/sensors/Bno055.cpp
> +    int Bno055::setPowerMode(PowerMode mode)
Good point... It's only milliamps.

2016-12-08 02:24 UTC, irwineffect commented on src/sensors/CMakeLists.txt
> +add_ros_node(bno bno_example.cpp Bno055.cpp)
can we rename this executable to bno_example for clarity?

2016-12-08 02:24 UTC, irwineffect approved these changes

2016-12-08 02:49 UTC, merged