Update control system
PalouseRobosub/robosub-2018 pull request #88
Opened 2016-12-05 05:16 UTC by ryan-summers

This changeset removes a number of bugs found in the control system and organizes code into a more understandable fashion. It is possible that we want to re-architect the control system as a whole in the future, but that does not necessary conflict with this pull request.

2016-12-05 23:28 UTC, skallaher requested changes

2016-12-05 23:28 UTC, skallaher commented on src/movement/control.cpp
> +    ROS_INFO("Received control message.");
With this as an `INFO` print, this would very quickly clutter up the terminal while running. `DEBUG` seems more suited for this.

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.hpp
> +    ControlSystem() = delete;
Why are you explicitly deleting the constructor here? You've created your own constructor below, the compiler shouldn't create an empty default constructor.

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.hpp
>      Vector6d offsets;
You've commented the rest of the variables, why not these ones?

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.hpp
> +	ControlSystem(ros::Publisher *pub);
Is there a reason to pass this as a pointer and not a reference?

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.cpp
> +    nh.getParamCached("hysteresis/theta", hysteresis[5]);
At the very least, some white space to break these up into chunks would be more readable. The previously existing comments, though a little redundant when seeing the parameter being loaded, were useful in making this code easier on the eyes.

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.cpp
> +    dt = 1.0/dt;
Why is this code in the constructor?

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.cpp
> + * @note This function updates he desired state Sd.
Typo here. Should be `the` not `he`. Also, what's the `Sd` for?

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.cpp
> +             * following bounding limits:
Perhaps also note here that Roll, Pitch, Yaw is equivalent to Psi, Phi, Theta.

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.cpp
>                  this->goal_types[i] = robosub::control::STATE_ABSOLUTE;
Why is this set to `STATE_ABSOLUTE` when the requested state is `STATE_RELATIVE`?

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.cpp
>      /*
Are these comments necessary?

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.hpp
>      robosub::thruster tp;
A more descriptive name would be useful here.

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.cpp
> +    return "Unknown State";
This is unreachable code.

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.cpp
> +    ROS_INFO_STREAM("Current State: \n" << state_vector);
This is being done every time the node spins. This will also clutter the terminal. I suggest using `DEBUG` rather than `INFO`

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.cpp
> +    ROS_INFO_STREAM("Integral States: \n" << current_integral);
See previous comment.

2016-12-05 23:28 UTC, skallaher commented on src/movement/control_system.cpp
> +VectorXd ControlSystem::calculate_motor_control()
This function is rather long, could some of it be broken up into smaller functions?

2016-12-07 01:24 UTC, ryan-summers commented on src/movement/control_system.cpp
> +VectorXd ControlSystem::calculate_motor_control()
I would actually argue this should all stay together as it's doing one single thing. It's a lot of stuff, but it should all be here to ensure everything is called in the correct order.

2016-12-07 07:06 UTC, skallaher requested changes
Though I can't verify either the parameter settings or some of the underlying mathematics, I did see some things that were puzzling just reading through.

2016-12-07 07:06 UTC, skallaher commented on src/movement/control.cpp
>      control_system->InputControlMessage(*msg);
Why not just have the `InputControlMessage` function call as the callback?

2016-12-07 07:06 UTC, skallaher commented on src/movement/control.cpp
>  void orientationCallback(const geometry_msgs::Quaternion::ConstPtr& quat_msg)
Would it be possible to have the node receive stamped quaternions? Otherwise, perhaps stamp them when they come in or does the constructor stamp the data? Similarly with the depth messages.

2016-12-07 07:06 UTC, skallaher commented on src/movement/control_system.cpp
> +        dt = 1.0/rate;
Does this not have a divide by zero issue? `rate` will currently always be zero at this point.

2016-12-07 07:06 UTC, skallaher commented on src/movement/control_system.cpp
> +        ROS_INFO_STREAM("Thruster Positions:\n" << position);
Is there a way that these values could be validated by a unit test in future?

2016-12-07 07:06 UTC, skallaher commented on src/movement/control_system.cpp
> +        ControlSystem::InputOrientationMessage(geometry_msgs::QuaternionStamped
Is this on a new line to hold to the 80 character limit?

2016-12-07 07:06 UTC, skallaher commented on src/movement/control_system.cpp
> +        state_vector[6] *= _180_OVER_PI;
A note that this is converting from radians to degrees and the rest of the system is in degrees seems suitable here.

2016-12-07 07:06 UTC, skallaher commented on src/movement/control_system.cpp
> +        state_vector[5] = prev_depth_msg.depth - depth_msg.depth;
Is this the delta depth or the derivative (delta depth/delta time)?

2016-12-07 07:06 UTC, skallaher commented on src/movement/control_system.cpp
> +        state_vector[1] = 0; //y
If these states are shared amongst the sensor data inputs, it seems odd that they would be set to zero rather than just left unchanged.

2016-12-07 07:06 UTC, skallaher commented on src/movement/control_system.cpp
> +                        -1 : 1);
Indenting this line further to line up with `(current_integral[i] < 0)` would make this easier to visualize

2016-12-07 07:06 UTC, skallaher commented on src/movement/control_system.cpp
> +         *       all goals are equally represented.
Are there any documented theories on how this might be done?

2016-12-07 07:06 UTC, skallaher commented on src/movement/control_system.cpp
> +        return "Unknown State";
You were correct, this code is reachable, my mistake. However, this is what the `default` case should be used for as it is a catch all other values situation.

2016-12-07 07:06 UTC, skallaher commented on src/movement/control_system.h
> +        static constexpr double _180_OVER_PI = (180.0 / 3.14159);
These are defined in the `rotation_engine.hpp` file. These seem redundant.

2016-12-07 07:06 UTC, skallaher commented on src/movement/rotation_engine.cpp
>  */
Is this comment needed anymore?

2016-12-07 07:06 UTC, skallaher commented on src/movement/rotation_engine.cpp
>  theta = yaw
This file looks like it could use some better documentation. Perhaps an issue for a later date, though it should be at least flagged as such for now.

2016-12-07 07:31 UTC, ryan-summers commented on src/movement/control.cpp
>  void orientationCallback(const geometry_msgs::Quaternion::ConstPtr& quat_msg)
I just finished the sensor node tonight, and it's sending stamped quaternions, so we'll need to update this node when that branch is added.

2016-12-07 07:32 UTC, ryan-summers commented on src/movement/control_system.cpp
> +        dt = 1.0/rate;
Rate is loaded from the parameter server, which is listed as 20. We could have a ros error if the rate is specified as zero, but if this is in the constructor there isn't much we can do to handle that case. Regardless, currently we need a dt value for calculating the integral.

2016-12-07 07:32 UTC, ryan-summers commented on src/movement/control_system.cpp
> +        ROS_INFO_STREAM("Thruster Positions:\n" << position);
I don't see how because they are factors of the real submarine.

2016-12-07 07:34 UTC, ryan-summers commented on src/movement/control_system.cpp
> +        ControlSystem::InputOrientationMessage(geometry_msgs::QuaternionStamped
No, this is an artifact of vim's wrapping. I'm correcting it.

2016-12-07 07:37 UTC, ryan-summers commented on src/movement/control_system.cpp
> +        state_vector[5] = prev_depth_msg.depth - depth_msg.depth;
Currently it's both if we define a single unit of time as the time between control system loops.

2016-12-07 07:39 UTC, ryan-summers commented on src/movement/control_system.cpp
> +                        -1 : 1);
This is using a standard wrap convention. I'll instead move the current_integral section down.

2016-12-07 07:39 UTC, ryan-summers commented on src/movement/control_system.cpp
> +         *       all goals are equally represented.
Not as of yet.

2016-12-07 07:40 UTC, ryan-summers commented on src/movement/control_system.cpp
> +        return "Unknown State";
I have decided to move it as the end'value return to ensure that for some reason there is always a return state. I'm more of a believe in keeping a return statement in the end of a function if there is guaranteed to be one.

2016-12-07 07:41 UTC, ryan-summers commented on src/movement/control_system.h
> +        static constexpr double _180_OVER_PI = (180.0 / 3.14159);
It strikes me that we should define these in a special header that can be used by many different tools.

2016-12-07 07:41 UTC, ryan-summers commented on src/movement/rotation_engine.cpp
>  theta = yaw
Will add comments. There's a few things I want to work on but this control system rework got out of hand as it is.

2016-12-07 08:05 UTC, ryan-summers commented on src/movement/control_system.cpp
> +        dt = 1.0/rate;
Incorrect. Rate is the update rate that the control node runs at.

2016-12-07 08:07 UTC, ryan-summers commented on src/movement/control_system.h
> +        static constexpr double _180_OVER_PI = (180.0 / 3.14159);
However, also note that these are class specific and those defined in rotation_engine are in the cpp, not the header. As of yet, they are all file-specific parameters.

2016-12-07 16:42 UTC, skallaher approved these changes
Just a few very minor things. Everything looks good to me so I'll approve my review. Any thoughts @irwineffect?

2016-12-07 16:42 UTC, skallaher commented on src/movement/control_system.cpp
> +            ROS_FATAL("Control system rate is specified as zero or less.");
Just a note that this could also be a result of the parameter not being specified as well.

2016-12-07 16:42 UTC, skallaher commented on src/movement/control_system.cpp
> +        state_vector[2] = depth_msg.depth;
I just want to be sure that my suggested change is still valid with the underlying math.

2016-12-07 16:42 UTC, skallaher commented on src/movement/rotation_engine.cpp
>  theta = yaw
The provided comment should suffice for this pull request.

2016-12-07 17:52 UTC, merged

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +        return "Unknown State";
The breaks are unnecessary in this section unless you just set a string variable and then return the contents of the variable, i.e.:
```c++
std::string ret = "Unknown State"
switch(state)
{
case robosub::control::STATE_NONE:
    ret = "No State";
    break;
case robosub::control::STATE_ERROR:
    ret = "Error State";
    break;
case robosub::control::STATE_ABSOLUTE:
    ret = "Absolute State";
    break;
case robosub::control::STATE_RELATIVE:
    ret = "Relative State";
    break;
default:
    break;
}
return ret;
```

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.h
> +    	ControlSystem();
There's a tab causing inconsistent spacing on this line.

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.h
> +
Extra newline

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.h
> +         * Defines the last calculated non-truncated translation control.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.h
> +         * Defines the last calculated non-truncated rotation control.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.h
> +         * Define the motor matrix (inverted) used to solve for the motor commands.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.h
> +         * Defines the maximum thrust a thruster can output in newtons.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.h
> +         * Defines the amount of time that passes between each control cycle.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.h
> +         * Defines the number of thrusters on the submarine.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.h
> +         * The previous quaternion orientation message received.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.h
> +         * The previous depth message received.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on msg/control_status.msg
> +float32[] translation_control
Is the ordering of these arrays defined somewhere?

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control.cpp
>          r.sleep();
`r` is undefined

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +        dt = 1.0/rate;
You should still guard against the possibility and throw a ROS_FATAL.

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +        ROS_INFO_STREAM("Thruster Positions:\n" << position);
The shape of the motors matrix could be checked as well as ensuring that the orientation is either 1 or -1.

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +                        goals[i] = state_vector[i] + control_values[i];
`this` is used on all of the other goals[i]. Add it here as well.

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +         * Convert accelerations to force by multipling by masses.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +         * Calculate the rotation control for each thruster.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +         * Update and bound-check the integral terms.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +         * Update the current error vector with the calculated errors.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +         * Update the derivatives of position within the state vector.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +         * Ensure that the commands and states are all set to zero initially.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +         * Initialize the state of the goals to error.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +         * Load parameters from the settings file.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on src/movement/control_system.cpp
> +     * Constructor.
This should be a single line comment

2016-12-07 18:10 UTC, bkallaher commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-Wall -std=c++11 ${CMAKE_CXX_FLAGS}")
This change doesn't belong in this pull request.

2016-12-07 19:21 UTC, ryan-summers commented on src/movement/control_system.cpp
> +     * Constructor.
This is a doxygen comment for a function.

2016-12-07 19:28 UTC, bkallaher commented on src/movement/control_system.cpp
> +     * Constructor.
Doxygen supports single line comments in the form of `/// Description`

2016-12-07 22:27 UTC, ryan-summers commented on src/movement/control_system.h
> +    	ControlSystem();
How did my vim not remove this! Good catch.

2016-12-07 22:28 UTC, ryan-summers commented on src/movement/control_system.h
> +
right you are

2016-12-07 22:28 UTC, ryan-summers commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-Wall -std=c++11 ${CMAKE_CXX_FLAGS}")
I realized after creating the pull request I accidentally left this in. Removing it now!